config { 
    type: "table",
    schema: "documentation_pii_leakage",
    tags: ["pii-leakage"],
}

SELECT
    t1.user_id,
    t1.email,
    t1.full_name,
    SUM(t3.sale_price) AS total_amount
FROM
    ${ref("users_with_full_name_v")} AS t1
INNER JOIN
    ${ref("stg_orders")} AS t2 ON t1.user_id = t2.user_id
INNER JOIN
    ${ref("stg_order_items")} AS t3 ON t2.order_id = t3.order_id
GROUP BY 1, 2, 3
